databases:
  - name: onyx-db
    plan: free
    databaseName: onyx_db
    user: onyx_user

services:
  - type: web
    plan: free
    name: onyx-api
    runtime: node
    rootDir: backend
    buildCommand: npm install && npm run build
    startCommand: npx prisma db push --skip-generate && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: onyx-db
          property: connectionString
      - key: JWT_SECRET
        generateValue: true
      - key: JWT_REFRESH_SECRET
        generateValue: true
      - key: CORS_ORIGIN
        sync: false
